FROM node:22.12-alpine

ENV NODE_ROOT=/app

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
ENV NEXT_TELEMETRY_DISABLED=1
ENV CHECKPOINT_DISABLE=1

WORKDIR $NODE_ROOT

RUN apk add --no-cache git

# issue with alpine and prisma ssl
# https://github.com/prisma/prisma/issues/25817
# remove once prisma 6.1 is fully shipped
RUN sh -c '[ ! -e /lib/libssl.so.3 ] && ln -s /usr/lib/libssl.so.3 /lib/libssl.so.3 || echo "Link already exists"'

EXPOSE 3000

CMD ["yarn", "dev"]
