FROM node:24.12-alpine

ENV NODE_ROOT=/app

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
ENV NEXT_TELEMETRY_DISABLED=1
ENV CHECKPOINT_DISABLE=1

WORKDIR $NODE_ROOT

RUN apk add --no-cache git

COPY docker-yarn-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-yarn-entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["docker-yarn-entrypoint.sh"]
CMD ["yarn", "dev"]
