enableGlobalCache: true

enableScripts: true

enableTelemetry: false

nodeLinker: node-modules

npmMinimalAgeGate: 1440

packageExtensions:
  prisma@7.10.0:
    dependencies:
      "@types/react": 19.2.18
      "@types/react-dom": 19.2.7
      react: 19.2.8
      react-dom: 19.2.8
