compressionLevel: mixed

enableGlobalCache: true

enableScripts: true

enableTelemetry: false

nodeLinker: node-modules

npmMinimalAgeGate: 1440

packageExtensions:
  prisma@7.10.0:
    dependencies:
      "@types/react": 19.3.0
      "@types/react-dom": 19.3.0
      react: 19.3.0
      react-dom: 19.3.0
