
import builder from '@/lib/graphql/builder';
import { Prisma } from '.prisma/client';
export {
  projectObject,
  projectIdFieldObject,
  projectNameFieldObject,
  projectApi_keyFieldObject,
  projectOrganizationFieldObject,
  projectRepo_providerFieldObject,
  projectRepo_provider_api_keyFieldObject,
  projectRepo_provider_api_secretFieldObject,
  projectRepo_branchFieldObject,
  projectRepo_issue_trackerFieldObject,
  projectRepo_urlFieldObject,
  projectNotices_countFieldObject,
  projectCreated_atFieldObject,
  projectUpdated_atFieldObject,
  projectNoticesFieldObject,
  createManyprojectMutation,
  createOneprojectMutation,
  deleteManyprojectMutation,
  deleteOneprojectMutation,
  updateManyprojectMutation,
  updateOneprojectMutation,
  upsertOneprojectMutation,
  createManyprojectMutationObject,
  createOneprojectMutationObject,
  deleteManyprojectMutationObject,
  deleteOneprojectMutationObject,
  updateManyprojectMutationObject,
  updateOneprojectMutationObject,
  upsertOneprojectMutationObject,
  findFirstprojectQuery,
  findManyprojectQuery,
  countprojectQuery,
  findUniqueprojectQuery,
  findFirstprojectQueryObject,
  findManyprojectQueryObject,
  countprojectQueryObject,
  findUniqueprojectQueryObject
} from './project';
export {
  noticeObject,
  noticeIdFieldObject,
  noticeProject_idFieldObject,
  noticeEnvFieldObject,
  noticeKindFieldObject,
  noticeSeen_countFieldObject,
  noticeCreated_atFieldObject,
  noticeUpdated_atFieldObject,
  noticeProjectFieldObject,
  noticeOccurrencesFieldObject,
  createManynoticeMutation,
  createOnenoticeMutation,
  deleteManynoticeMutation,
  deleteOnenoticeMutation,
  updateManynoticeMutation,
  updateOnenoticeMutation,
  upsertOnenoticeMutation,
  createManynoticeMutationObject,
  createOnenoticeMutationObject,
  deleteManynoticeMutationObject,
  deleteOnenoticeMutationObject,
  updateManynoticeMutationObject,
  updateOnenoticeMutationObject,
  upsertOnenoticeMutationObject,
  findFirstnoticeQuery,
  findManynoticeQuery,
  countnoticeQuery,
  findUniquenoticeQuery,
  findFirstnoticeQueryObject,
  findManynoticeQueryObject,
  countnoticeQueryObject,
  findUniquenoticeQueryObject
} from './notice';
export {
  occurrenceObject,
  occurrenceIdFieldObject,
  occurrenceNotice_idFieldObject,
  occurrenceMessageFieldObject,
  occurrenceSeen_countFieldObject,
  occurrenceBacktraceFieldObject,
  occurrenceContextFieldObject,
  occurrenceEnvironmentFieldObject,
  occurrenceSessionFieldObject,
  occurrenceParamsFieldObject,
  occurrenceCreated_atFieldObject,
  occurrenceUpdated_atFieldObject,
  occurrenceNoticeFieldObject,
  occurrenceHourly_occurrencesFieldObject,
  createManyoccurrenceMutation,
  createOneoccurrenceMutation,
  deleteManyoccurrenceMutation,
  deleteOneoccurrenceMutation,
  updateManyoccurrenceMutation,
  updateOneoccurrenceMutation,
  upsertOneoccurrenceMutation,
  createManyoccurrenceMutationObject,
  createOneoccurrenceMutationObject,
  deleteManyoccurrenceMutationObject,
  deleteOneoccurrenceMutationObject,
  updateManyoccurrenceMutationObject,
  updateOneoccurrenceMutationObject,
  upsertOneoccurrenceMutationObject,
  findFirstoccurrenceQuery,
  findManyoccurrenceQuery,
  countoccurrenceQuery,
  findUniqueoccurrenceQuery,
  findFirstoccurrenceQueryObject,
  findManyoccurrenceQueryObject,
  countoccurrenceQueryObject,
  findUniqueoccurrenceQueryObject
} from './occurrence';
export {
  hourly_occurrenceObject,
  hourly_occurrenceIdFieldObject,
  hourly_occurrenceOccurrence_idFieldObject,
  hourly_occurrenceInterval_startFieldObject,
  hourly_occurrenceInterval_endFieldObject,
  hourly_occurrenceCountFieldObject,
  hourly_occurrenceOccurrenceFieldObject,
  createManyhourly_occurrenceMutation,
  createOnehourly_occurrenceMutation,
  deleteManyhourly_occurrenceMutation,
  deleteOnehourly_occurrenceMutation,
  updateManyhourly_occurrenceMutation,
  updateOnehourly_occurrenceMutation,
  upsertOnehourly_occurrenceMutation,
  createManyhourly_occurrenceMutationObject,
  createOnehourly_occurrenceMutationObject,
  deleteManyhourly_occurrenceMutationObject,
  deleteOnehourly_occurrenceMutationObject,
  updateManyhourly_occurrenceMutationObject,
  updateOnehourly_occurrenceMutationObject,
  upsertOnehourly_occurrenceMutationObject,
  findFirsthourly_occurrenceQuery,
  findManyhourly_occurrenceQuery,
  counthourly_occurrenceQuery,
  findUniquehourly_occurrenceQuery,
  findFirsthourly_occurrenceQueryObject,
  findManyhourly_occurrenceQueryObject,
  counthourly_occurrenceQueryObject,
  findUniquehourly_occurrenceQueryObject
} from './hourly_occurrence';

export const BatchPayload = builder.objectType(builder.objectRef<Prisma.BatchPayload>('BatchPayload'), {
  description: 'Batch payloads from prisma.',
  fields: (t) => ({
    count: t.exposeInt('count', { description: 'Prisma Batch Payload', nullable: false }),
  }),
});

export const modelNames = [
  'project',
  'notice',
  'occurrence',
  'hourly_occurrence',
] as const;

export type Model = typeof modelNames[number];
